### ISSUE TITLE
Question: How do I cite the pyrosetta-help package?

### ISSUE THREAD

**Issue by engelberger** [matteoferla/pyrosetta-help#2]
Dear Matteo,

I have used one of the scripts included in this package (Threading in pyrosetta) for one of my studies and I was wondering how should I properly cite your package. Thank you in advance!

Kind regards.

**Comment by matteoferla** [comment]
Thanks for asking —hearing of someone using is reward enough!

I just assembled code I used with PyRosetta, which required some reverse engineering to figure out. The original authors of RosettaCM (comparative modelling) and PyRosetta would be more deserving.
